name: autopep8
on: pull_request
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install autopep8
        run: pip install autopep8
      - name: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Check for changes
        id: git-check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "The following linting errors were found:"
            # Capture and display the diff output
            DIFF_OUTPUT=$(autopep8 --exit-code --recursive --diff --aggressive --aggressive .)
            echo "$DIFF_OUTPUT"
            exit 1
          else
            echo "No changes were made by autopep8."
          fi