name: autopep8
on: pull_request
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install autopep8
        run: pip install autopep8
      - name: Run autopep8 and check for changes
        run: |
          # Run autopep8 and capture the diff output into a file
          autopep8 --exit-code --recursive --diff --aggressive --aggressive . > autopep8_diff_output.txt
          # Check if the file has content (i.e., there are changes)
          if [[ -s autopep8_diff_output.txt ]]; then
            echo "Linting failed, see diff changes below:"
            # Display the contents of the diff output file
            cat autopep8_diff_output.txt
            exit 1
          else
            echo "No changes were made by autopep8."
          fi